### ISSUE TITLE
[object Object]

### ISSUE THREAD

**Issue by alalaha** [juna1221/ythNotify#3]
Need help.
console.log("Start streaming! \n" + data)
Returns as 
Start streaming!
[object Object]

**Comment by dongsu8142** [comment]
Then try console.log(data)

**Comment by alalaha** [comment]
@hands8142 I'm trying to keep the streams saved in the database to change them easily by a command, but when I add: 
```
clientid: "XXXXXX",
streamers: streamdb.lives,
},
```
I get errors like: Cannot read property 'split' of undefined 
ythnotify\src\client\Client.js:114:17
ythnotify\src\database\DBManager.js:18:18

or 

Either YouTube or Twitch must be added.
ythnotify\src\client\Client.js:64:13

could you help me?

**Comment by dongsu8142** [comment]
I don't know what you want to talk about.

**Comment by juna1221** [comment]
@hands8142 [object Object]로 뜨는 이슈랑 `Either YouTube or Twitch must be added.` 오류가 뜨는 이유(해결방법) 알려달라는거잖아요..

**Comment by juna1221** [comment]
> @hands8142 I'm trying to keep the streams saved in the database to change them easily by a command, but when I add:
> 
> ```
> clientid: "XXXXXX",
> streamers: streamdb.lives,
> },
> ```
> 
> I get errors like: Cannot read property 'split' of undefined
> ythnotify\src\client\Client.js:114:17
> ythnotify\src\database\DBManager.js:18:18
> 
> or
> 
> Either YouTube or Twitch must be added.
> ythnotify\src\client\Client.js:64:13
> 
> could you help me?

try this:

```js
const yth = new Yth.Client({
  twitch: {
    secreat: "Secreat (Twitch API)",
    clientid: "Client ID (Twitch API)",
    streamers: "https://www.twitch.tv/whitekj",
  },
  interval: 20,
})
```
